version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: flyway_postgres
    environment:
      POSTGRES_DB: FlywayApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6737
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - flyway-net

  app:
    build: .
    container_name: flyway_app
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/FlywayApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 6737
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SERVER_PORT: 8083
    networks:
      - flyway-net

volumes:
  pgdata:

networks:
  flyway-net:
